### ISSUE TITLE
Navigation button (3bar) is not working here.

### ISSUE THREAD

**Issue by Kapilrohilla** [Raymacmillan/Drop-down-Navigation-Menu#1]
Hey Ray,
In this project, navigation bar isn't working in at mobile layout
![image](https://user-images.githubusercontent.com/110235703/204857021-bd144781-dcbb-450c-978f-6300ba3d7a91.png)

also, the dropdown menu feature & company isn't working in Desktop Layout
![image](https://user-images.githubusercontent.com/110235703/204857202-b956f1f8-eba9-4a85-9b39-d17763e3e860.png)

**Comment by Raymacmillan** [comment]
Thank you so much for making me aware...let me try and look into it

Raymacmillan
Software Developer
